apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: work-pool
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://workpool:workpool_secret@mongodb:27017/workpool_notifications?authSource=admin"

