apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - work-pool-user-service.yaml
  - work-pool-task-service.yaml
  - work-pool-notification-service.yaml
  - work-pool-payment-service.yaml
  - work-pool-rating-service.yaml
  - work-pool-api-gateway.yaml
  - work-pool-ui.yaml

