apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - user-service.yaml
  - task-service.yaml
  - notification-service.yaml
  - payment-service.yaml
  - rating-service.yaml
  - api-gateway.yaml
  - work-pool-ui.yaml

