apiVersion: v1
kind: ConfigMap
metadata:
  name: work-pool-shared-config
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  HAZELCAST_CLUSTER_NAME: work-pool-cluster
  HAZELCAST_CLUSTER_MEMBERS: hazelcast:5701
  SPRING_MAIL_HOST: mailhog
  SPRING_MAIL_PORT: "1025"
  USER_SERVICE_URL: http://work-pool-user-service:8081
  TASK_SERVICE_URL: http://work-pool-task-service:8082
  NOTIFICATION_SERVICE_URL: http://work-pool-notification-service:8083
  PAYMENT_SERVICE_URL: http://work-pool-payment-service:8084
  RATING_SERVICE_URL: http://work-pool-rating-service:8085
  OAUTH2_SUCCESS_REDIRECT_URL: http://ui.work-pool.org/auth/oauth2/callback
  OAUTH2_FAILURE_REDIRECT_URL: http://ui.work-pool.org/login
  OAUTH2_BASE_URL: http://api.work-pool.org

